hc/urls.py
from django.contrib import admin
from django.urls import include, path

from hc.accounts.views import login as hc_login

urlpatterns = [
    path('admin/login/', hc_login),
    path('admin/', admin.site.urls),
    path('accounts/', include('hc.accounts.urls')),
    path('', include('hc.api.urls')),
    path('', include('hc.front.urls')),
    path('', include('hc.payments.urls'))
]

hc/front/forms.py
from datetime import timedelta as td
import json
import re

from django import forms
from django.core.validators import RegexValidator
from hc.front.validators import (CronExpressionValidator, TimezoneValidator,
                                 WebhookValidator)


class NameTagsForm(forms.Form):
    name = forms.CharField(max_length=100, required=False)
    tags = forms.CharField(max_length=500, required=False)
    desc = forms.CharField(required=False)

    def clean_tags(self):
        result = []

        for part in self.cleaned_data["tags"].split(" "):
            part = part.strip()
            if part != "":
                result.append(part)

        return " ".join(result)


class EmailSettingsForm(forms.Form):
    subject = forms.CharField(max_length=100)


class TimeoutForm(forms.Form):
    timeout = forms.IntegerField(min_value=60, max_value=2592000)
    grace = forms.IntegerField(min_value=60, max_value=2592000)

    def clean_timeout(self):
        return td(seconds=self.cleaned_data["timeout"])

    def clean_grace(self):
        return td(seconds=self.cleaned_data["grace"])


class CronForm(forms.Form):
    schedule = forms.CharField(max_length=100,
                               validators=[CronExpressionValidator()])
    tz = forms.CharField(max_length=36, validators=[TimezoneValidator()])
    grace = forms.IntegerField(min_value=1, max_value=43200)


class AddOpsGenieForm(forms.Form):
    error_css_class = "has-error"
    value = forms.CharField(max_length=40)


class AddEmailForm(forms.Form):
    error_css_class = "has-error"
    value = forms.EmailField(max_length=100)


class AddUrlForm(forms.Form):
    error_css_class = "has-error"
    value = forms.URLField(max_length=1000, validators=[WebhookValidator()])


_valid_header_name = re.compile(r'\A[^:\s][^:\r\n]*\Z').match


class AddWebhookForm(forms.Form):
    error_css_class = "has-error"

    url_down = forms.URLField(max_length=1000, required=False,
                              validators=[WebhookValidator()])

    url_up = forms.URLField(max_length=1000, required=False,
                            validators=[WebhookValidator()])

    post_data = forms.CharField(max_length=1000, required=False)

    def __init__(self, *args, **kwargs):
        super(AddWebhookForm, self).__init__(*args, **kwargs)

        self.invalid_header_names = set()
        self.headers = {}
        if "header_key[]" in self.data and "header_value[]" in self.data:
            keys = self.data.getlist("header_key[]")
            values = self.data.getlist("header_value[]")
            for key, value in zip(keys, values):
                if not key:
                    continue

                if not _valid_header_name(key):
                    self.invalid_header_names.add(key)

                self.headers[key] = value

    def clean(self):
        if self.invalid_header_names:
            raise forms.ValidationError("Invalid header names")

        return self.cleaned_data

    def get_value(self):
        val = dict(self.cleaned_data)
        val["headers"] = self.headers
        return json.dumps(val, sort_keys=True)


phone_validator = RegexValidator(regex='^\+\d{5,15}$',
                                 message="Invalid phone number format.")


class AddSmsForm(forms.Form):
    error_css_class = "has-error"
    label = forms.CharField(max_length=100, required=False)
    value = forms.CharField(max_length=16, validators=[phone_validator])


class ChannelNameForm(forms.Form):
    name = forms.CharField(max_length=100, required=False)

templates/integrations/add_discord.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}Add Discord - {% site_name %}{% endblock %}


{% block content %}
<div class="row">
<div class="col-sm-12">
    <h1>Discord</h1>

    <div class="jumbotron">
        <p>
            With this integration, {% site_name %} will send
            a notification to a <a href="http://discord.com/">Discord</a>
            channel when a check
            goes <strong>up</strong> or <strong>down</strong>.
        </p>

        <form method="post" class="text-center">
            {% csrf_token %}
            <a href="{{ authorize_url }}" class="btn btn-lg btn-default">
                <img class="ai-icon" src="{% static 'img/integrations/discord.png' %}" alt="Discord" />
                Connect Discord
            </a>
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/integrations/add_email.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}Notification Channels - {% site_name %}{% endblock %}


{% block content %}
<div class="row">
<div class="col-sm-12">
    <h1>Email</h1>

    <p>Get an email message when check goes up or down.</p>

    <p>
        <strong>Tip:</strong>
        Add multiple email addresses, to notify multiple team members.
    </p>

    <p>
        <strong>Confirmation needed.</strong>
        After entering an email address, {% site_name %} will send out a confirmation link.
        Only confirmed addresses will receive notifications.
    </p>

    <h2>Integration Settings</h2>

    <form method="post" class="form-horizontal" action="{% url 'hc-add-email' %}">
        {% csrf_token %}
        <div class="form-group {{ form.value.css_classes }}">
            <label for="id_email" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-3">
                <input
                    id="id_email"
                    type="email"
                    class="form-control"
                    name="value"
                    placeholder="you@example.org"
                    value="{{ form.value.value|default:"" }}">

                {% if form.value.errors %}
                <div class="help-block">
                    {{ form.value.errors|join:"" }}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Save Integration</button>
            </div>
        </div>
    </form>
</div>
</div>
{% endblock %}

templates/integrations/add_opsgenie.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}Add OpsGenie - {% site_name %}{% endblock %}


{% block content %}
<div class="row">
<div class="col-sm-12">
    <h1>OpsGenie</h1>

    <p><a href="https://www.opsgenie.com/">OpsGenie</a> provides
    alerting, on-call scheduling, escalation policies and incident tracking.
    You can can integrate it with your {% site_name %} account in few
    simple steps.</p>

    <h2>Setup Guide</h2>
    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">1</span>
            <p>
                Log into your OpsGenie account,
                go to <strong>Integrations &gt; Add New Integrations</strong>,
                and add the "API" integration.
            </p>
            <p>
                Give it a descriptive name, then
                save the integration.
            </p>

        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_opsgenie_1.png' %}">
        </div>
    </div>
    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">2</span>
            After adding the new integration, take note of its
            <strong>API key</strong>, a long string
            of letters and digits.

        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_opsgenie_2.png' %}">
        </div>
    </div>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">3</span>
            <p>Paste the API key down below. Save the integration, and
            you are done!</p>
        </div>
    </div>

    <h2>Integration Settings</h2>

    <form method="post" class="form-horizontal" action="{% url 'hc-add-opsgenie' %}">
        {% csrf_token %}
        <div class="form-group {{ form.value.css_classes }}">
            <label for="api-key" class="col-sm-2 control-label">API Key</label>
            <div class="col-sm-4">
                <input
                    id="api-key"
                    type="text"
                    class="form-control"
                    name="value"
                    placeholder=""
                    value="{{ form.value.value|default:"" }}">

                {% if form.value.errors %}
                <div class="help-block">
                    {{ form.value.errors|join:"" }}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Save Integration</button>
            </div>
        </div>
    </form>
</div>
</div>
{% endblock %}

templates/integrations/add_pagertree.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}Add PagerTree - {% site_name %}{% endblock %}


{% block content %}
<div class="row">
  <div class="col-sm-12">
      <h1>PagerTree</h1>

      <p>If your team uses <a href="https://pagertree.com">PagerTree</a>,
      you can set up {% site_name %} to create a PagerTree incident when
      a check goes down, and resolve it when a check goes back up.</p>

      <h2>Setup Guide</h2>

      <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">1</span>
            <p>
                Log into your PagerTree account, select the team you wish to add this integration to. Click the <strong>Integrations</strong> tab. Then click the <strong>+ Integration</strong> button.
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Click create integration button"
                src="{% static 'img/integrations/setup_pagertree_1.png' %}">
        </div>
      </div>

      <div class="row ai-step">
          <div class="col-sm-6">
              <span class="step-no">2</span>
              <p>
                  In the Create Integration Form, fill out the details with apprpriate values, but most importantly make sure the <strong>Integration Type</strong> is set to <strong>Healthchecks.io</strong>. Then click the <strong>Create</strong> button.
              </p>
          </div>
          <div class="col-sm-6">
              <img
                  class="ai-guide-screenshot"
                  alt="Create Healthchecks.io integration with details"
                  src="{% static 'img/integrations/setup_pagertree_2.png' %}">
          </div>
      </div>

      <div class="row ai-step">
          <div class="col-sm-6">
              <span class="step-no">3</span>
              <p>
                Copy the <strong>Webhook URL</strong> and paste it below. Save the integration, and you are done!
              </p>
          </div>
          <div class="col-sm-6">
              <img
                  class="ai-guide-screenshot"
                  alt="Copy the Webhook URL"
                  src="{% static 'img/integrations/setup_pagertree_3.png' %}">
          </div>
      </div>

      <h2>Integration Settings</h2>

      <form method="post" class="form-horizontal" action="{% url 'hc-add-pagertree' %}">
          {% csrf_token %}
          <div class="form-group {{ form.value.css_classes }}">
              <label for="post-url" class="col-sm-2 control-label">URL</label>
              <div class="col-sm-10">
                  <input
                      id="post-url"
                      type="text"
                      class="form-control"
                      name="value"
                      placeholder="https://"
                      value="{{ form.value.value|default:"" }}">

                  {% if form.value.errors %}
                  <div class="help-block">
                      {{ form.value.errors|join:"" }}
                  </div>
                  {% endif %}
              </div>
          </div>
          <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-primary">Save Integration</button>
              </div>
          </div>
      </form>
  </div>
</div>
{% endblock %}

templates/integrations/add_pushover.html
{% extends "base.html" %}
{% load compress humanize static hc_extras %}

{% block title %}Add Pushover - {% site_name %}{% endblock %}


{% block content %}
<div class="row">
<div class="col-sm-12">
    <div class="jumbotron">
        {% if request.user.is_authenticated %}
        <p>
            <a href="https://www.pushover.net/">Pushover</a> delivers
            real-time notifications on your Android, iPhone, iPad, Desktop,
            Android Wear and Apple Watch. You can set up {% site_name %} to
            receive Pushover notifications in a few simple steps.
        </p>
        {% else %}
        <p>
        {% site_name %} is a <strong>free</strong> and
        <a href="https://github.com/healthchecks/healthchecks">open source</a>
        service for monitoring your cron jobs, background processes and
        scheduled tasks. Before adding Pushover integration, please log into
        {% site_name %}:</p>

        <div class="text-center">
            <a href="{% url 'hc-login' %}?next={% url 'hc-add-pushover' %}"
               class="btn btn-primary btn-lg">Sign In</a>
        </div>
        {% endif %}
    </div>

    {% if not request.user.is_authenticated %}
    <h2>Setup Guide</h2>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">1</span>
            <p>
                After logging in, go to "Integrations &rarr; Add Pushover".
                Pushover supports different notification priorities from
                silent to "Emergency". Select your preferred priorities
                and click "Subscribe with Pushover".
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_pushover_1.png' %}">
        </div>
    </div>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">2</span>
            <p>
                You will be redirected to
                <a href="https://pushover.net">pushover.net</a> and
                asked to confirm a subscription. Review the subscription
                details and click "Subscribe Me".
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_pushover_2.png' %}">
        </div>
    </div>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">3</span>
            <p>
                That is all! You will now be redirected back to
                "Integrations" page on {% site_name %} and see
                the new integration!
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_pushover_3.png' %}">
        </div>
    </div>

    {% else %}
    <h2>Integration Settings</h2>

    <form id="add-pushover" method="post" class="form-horizontal" action="{% url 'hc-add-pushover' %}">
        {% csrf_token %}
        <div class="form-group">
            <label class="col-sm-3 control-label">Priority for "down" events</label>
            <div class="col-sm-8">
                <select name="po_priority" class="selectpicker form-control">
                    <option
                        value="-2"
                        data-content="Lowest Priority. <span class='help'>Generates no notification on your device.</span>">
                        Lowest Priority
                    </option>
                    <option
                        value="-1"
                        data-content="Low Priority. <span class='help'>Sends a quiet notification.</span>">
                        Low Priority
                    </option>
                    <option value="0" selected="selected">
                        Normal Priority
                    </option>
                    <option
                        value="1"
                        data-content="High Priority. <span class='help'>Bypasses user's quiet hours.</span>">
                        High Priority
                    </option>
                    <option
                        value="2"
                        data-content="Emergency Priority. <span class='help'>Repeated every {{po_retry_delay|hc_duration }} for at most {{ po_expiration|hc_duration }} until you acknowledge them.</span>">
                        Emergency Priority
                    </option>
                </select>
           </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label">Priority for "up" events</label>
            <div class="col-sm-8">
                <select name="po_priority_up" class="selectpicker form-control">
                    <option
                        value="-2"
                        data-content="Lowest Priority. <span class='help'>Generates no notification on your device.</span>">
                        Lowest Priority
                    </option>
                    <option
                        value="-1"
                        data-content="Low Priority. <span class='help'>Sends a quiet notification.</span>">
                        Low Priority
                    </option>
                    <option value="0" selected="selected">
                        Normal Priority
                    </option>
                    <option
                        value="1"
                        data-content="High Priority. <span class='help'>Bypasses user's quiet hours.</span>">
                        High Priority
                    </option>
                    <option
                        value="2"
                        data-content="Emergency Priority. <span class='help'>Repeated every {{po_retry_delay|hc_duration }} for at most {{ po_expiration|hc_duration }} until you acknowledge them.</span>">
                        Emergency Priority
                    </option>
                </select>
           </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-8">
                <button type="submit" class="btn btn-default">
                    <img class="ai-icon" src="{% static 'img/integrations/po.png' %}" alt="Pushover" />
                    Subscribe with Pushover
                </button>
            </div>
        </div>
    </form>
    {% endif %}
</div>
</div>
{% endblock %}

{% block scripts %}
{% compress js %}
<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap-select.min.js' %}"></script>
{% endcompress %}
{% endblock %}

templates/integrations/add_sms.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}Notification Channels - {% site_name %}{% endblock %}


{% block content %}
<div class="row">
<div class="col-sm-12">
    <h1>SMS</h1>

    <p>
        Get a SMS message to the specified phone number when a
        check goes down.
    </p>

    {% if show_pricing and profile.sms_limit == 0 %}
    <p class="alert alert-success">
        <strong>Paid plan required.</strong>
        SMS messaging is not available on the free plan–sending the messages
        cost too much! Please upgrade to a
        <a href="{% url 'hc-billing' %}">paid plan</a> to enable SMS messaging.
    </p>
    {% endif %}

    <h2>Integration Settings</h2>

    <form method="post" class="form-horizontal" action="{% url 'hc-add-sms' %}">
        {% csrf_token %}
        <div class="form-group {{ form.label.css_classes }}">
            <label for="id_label" class="col-sm-2 control-label">Label</label>
            <div class="col-sm-6">
                <input
                    id="id_label"
                    type="text"
                    class="form-control"
                    name="label"
                    placeholder="Alice's Phone"
                    value="{{ form.label.value|default:"" }}">

                {% if form.label.errors %}
                <div class="help-block">
                    {{ form.label.errors|join:"" }}
                </div>
                {% else %}
                <span class="help-block">
                    Optional. If you add multiple phone numbers,
                    the labels will help you tell them apart.
                </span>
                {% endif %}
            </div>
        </div>
        <div class="form-group {{ form.value.css_classes }}">
            <label for="id_number" class="col-sm-2 control-label">Phone Number</label>
            <div class="col-sm-3">
                <input
                    id="id_number"
                    type="tel"
                    class="form-control"
                    name="value"
                    placeholder="+1234567890"
                    value="{{ form.value.value|default:"" }}">

                {% if form.value.errors %}
                <div class="help-block">
                    {{ form.value.errors|join:"" }}
                </div>
                {% else %}
                <span class="help-block">
                    Make sure the phone number starts with "+" and  has the
                    country code.
                </span>
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Save Integration</button>
            </div>
        </div>
    </form>
</div>
</div>
{% endblock %}

templates/integrations/add_victorops.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}Add VictorOps - {% site_name %}{% endblock %}


{% block content %}
<div class="row">
<div class="col-sm-12">
    <h1>VictorOps</h1>

    <p><a href="https://victorops.com/">VictorOps</a> is
    another incident management system similar to PagerDuty.
    If you use or plan on using VictorOps, you can can integrate it
    with your {% site_name %} account in few simple steps.</p>

    <h2>Setup Guide</h2>
    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">1</span>
            <p>
                Log into your VictorOps account,
                go to <strong>Settings > Schedules</strong>,
                and find or create the Team Schedule you
                would like to use for {% site_name %} alerts.
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_victorops_1.png' %}">
        </div>
    </div>
    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">2</span>
            <p>
                Go to <strong>Settings &gt; Integrations</strong> and scroll
                to the bottom of the page. Choose an existing
                <strong>Routing Key</strong> or
                add a new one, and make note of it.
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_victorops_2.png' %}">
        </div>
    </div>
    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">3</span>
            In the right hand side of
            <strong>Settings &gt; Integrations</strong> page,
            select <strong>REST Endpoint</strong>, and click on
            <strong>Enable Integration</strong>.
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_victorops_3.png' %}">
        </div>
    </div>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no">4</span>
            <p>Paste the <strong>Post URL</strong> from step 3 in the field
            below, being careful to replace <strong>$routing_key</strong>
            with your actual Routing Key from step 2. Save the integration,
            and it's done!</p>
        </div>
    </div>

    <h2>Integration Settings</h2>

    <form method="post" class="form-horizontal" action="{% url 'hc-add-victorops' %}">
        {% csrf_token %}
        <div class="form-group {{ form.value.css_classes }}">
            <label for="post-url" class="col-sm-2 control-label">Post URL</label>
            <div class="col-sm-10">
                <input
                    id="post-url"
                    type="text"
                    class="form-control"
                    name="value"
                    placeholder="https://"
                    value="{{ form.value.value|default:"" }}">

                {% if form.value.errors %}
                <div class="help-block">
                    {{ form.value.errors|join:"" }}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Save Integration</button>
            </div>
        </div>
    </form>
</div>
</div>
{% endblock %}

templates/integrations/pagertree_description.html
{% load humanize %}
{{ check.name_then_code }} is {{ check.status|upper }}.
{% if check.status == "down" %}
Last ping was {{ check.last_ping|naturaltime }}.
{% endif %}

templates/integrations/pagertree_title.html
{{ check.name_then_code }} is {{ check.status|upper }}

templates/integrations/pd_description.html
{% if check.status == "down" %}
    {{ check.name_then_code }} is DOWN
{% else %}
    {{ check.name_then_code }} received a ping and is now UP
{% endif %}

templates/integrations/pushbullet_message.html
{% load humanize %}

{% if check.status == "down" %}
The check "{{ check.name_then_code }}" is DOWN. Last ping was {{ check.last_ping|naturaltime }}
{% else %}
The check "{{ check.name_then_code }}" received a ping and is now UP.
{% endif %}

templates/integrations/trello_name.html
{% if check.status == "down" %}
    Down: {{ check.name_then_code }}
{% else %}
    Up: {{ check.name_then_code }}
{% endif %}

templates/integrations/zendesk_description.html
{% load humanize %}
{% if check.status == "down" %}
    {{ check.name_then_code }} is down.
    Last ping was {{ check.last_ping|naturaltime }}.
    Details: {{ check.details_url }}
{% else %}
    {{ check.name_then_code }} received a ping and is now UP
{% endif %}

templates/integrations/zendesk_title.html
{% if check.status == "down" %}
    {{ check.name_then_code }} is down
{% else %}
    {{ check.name_then_code }} is now UP
{% endif %}